<?php

namespace Inertia\WinspireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuitcaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuitcaseRepository extends EntityRepository
{
    
}
