# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

home:
    pattern:  /
    defaults: { _controller: InertiaWinspireBundle:Default:index }
    
contactUs:
    pattern:  /contact-us
    defaults: { _controller: InertiaWinspireBundle:Contact:index }
    
contactSuccess:
    pattern:  /contact-success
    defaults: { _controller: InertiaWinspireBundle:Contact:success }
    
packageList:
    pattern:  /packages/{slug}
    defaults: { _controller: InertiaWinspireBundle:Default:packageList, slug: all }
    
packageListJson:
    pattern:  /packages.json
    defaults: { _controller: InertiaWinspireBundle:Default:packageListJson }
    
packageDownload:
    pattern:  /package/download/{versionId}
    defaults: { _controller: InertiaWinspireBundle:Default:packageDownload }
    
packageSearch:
    pattern:  /package/search
    defaults: { _controller: InertiaWinspireBundle:Default:packageSearch }
    
packageSearchJson:
    pattern:  /package/search.json
    defaults: { _controller: InertiaWinspireBundle:Default:packageSearchJson }
    
packageDetail:
    pattern:  /package/{slug}
    defaults: { _controller: InertiaWinspireBundle:Default:packageDetail }
    
suitcaseAdmin:
    pattern:  /admin/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:admin, id: none }
    
suitcaseView:
    pattern:  /suitcase
    defaults: { _controller: InertiaWinspireBundle:Suitcase:view }
    
suitcaseAdd:
    pattern:  /suitcase/add/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:add }
    
suitcaseCreate:
    pattern:  /suitcase/create
    defaults: { _controller: InertiaWinspireBundle:Suitcase:create }
    
suitcaseDelete:
    pattern:  /suitcase/delete/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:delete }
    
suitcaseDownload:
    pattern:  /suitcase/download/{suitcaseId}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:download }
    
suitcaseKill:
    pattern:  /suitcase/kill/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:kill }
    
suitcaseEdit:
    pattern:  /suitcase/edit
    defaults: { _controller: InertiaWinspireBundle:Suitcase:edit }
    
suitcaseFlag:
    pattern:  /suitcase/flag/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:flag }
    
suitcaseFlags:
    pattern:  /suitcase/flags
    defaults: { _controller: InertiaWinspireBundle:Suitcase:flags }
    
suitcasePack:
    pattern:  /suitcase/pack
    defaults: { _controller: InertiaWinspireBundle:Suitcase:pack }
    
suitcasePreview:
    pattern:  /suitcase/preview
    defaults: { _controller: InertiaWinspireBundle:Suitcase:preview }
    
suitcaseRequestInvoice:
    pattern:  /suitcase/request-invoice
    defaults: { _controller: InertiaWinspireBundle:Suitcase:requestInvoice }
    
suitcaseShare:
    pattern:  /suitcase/share
    defaults: { _controller: InertiaWinspireBundle:Suitcase:share }
    
suitcaseShareAgain:
    pattern:  /suitcase/reshare/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:shareAgain }
    
suitcaseSwitch:
    pattern:  /suitcase/switch
    defaults: { _controller: InertiaWinspireBundle:Suitcase:switch }
    
suitcaseUpdateQty:
    pattern:  /suitcase/update-qty/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:updateQty }
    
shareComment:
    pattern:  /comment/{id}/{token}
    defaults: { _controller: InertiaWinspireBundle:Share:comment, token: none }
    
shareView:
    pattern:  /share/{token}
    defaults: { _controller: InertiaWinspireBundle:Share:view }
    
accountCreate:
    pattern:  /account/new
    defaults: { _controller: InertiaWinspireBundle:Account:create }
    
accountEdit:
    pattern:  /account/edit
    defaults: { _controller: InertiaWinspireBundle:Account:edit }
    
accountValidate:
    pattern:  /account/validate
    defaults: { _controller: InertiaWinspireBundle:Account:validate }
    
emailValidate:
    pattern:  /account/validate-email
    defaults: { _controller: InertiaWinspireBundle:Account:validateEmail }
    
soap_account:
    pattern:  /soap/account
    defaults: { _controller: InertiaWinspireBundle:Soap:account }
    
soap_booking:
    pattern:  /soap/booking
    defaults: { _controller: InertiaWinspireBundle:Soap:booking }
    
soap_contact:
    pattern:  /soap/contact
    defaults: { _controller: InertiaWinspireBundle:Soap:contact }
    
soap_invoice:
    pattern:  /soap/invoice
    defaults: { _controller: InertiaWinspireBundle:Soap:invoice }
    
soap_package:
    pattern:  /soap/package
    defaults: { _controller: InertiaWinspireBundle:Soap:package }
    
soap_suitcase:
    pattern:  /soap/suitcase
    defaults: { _controller: InertiaWinspireBundle:Soap:suitcase }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    
fos_user_profile_show:
    pattern:  /account
    defaults: { _controller: InertiaWinspireBundle:Account:index }
    
pageDisplay:
    pattern:  /{slug}
    defaults: { _controller: InertiaWinspireBundle:Page:display }
