# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

home:
    pattern:  /
    defaults: { _controller: InertiaWinspireBundle:Default:index }
    
packageList:
    pattern:  /packages/{slug}
    defaults: { _controller: InertiaWinspireBundle:Default:packageList, slug: all }
    
packageListJson:
    pattern:  /packages.json
    defaults: { _controller: InertiaWinspireBundle:Default:packageListJson }
    
packageDetail:
    pattern:  /package/{slug}
    defaults: { _controller: InertiaWinspireBundle:Default:packageDetail }
    
suitcaseView:
    pattern:  /suitcase
    defaults: { _controller: InertiaWinspireBundle:Suitcase:view }
    
suitcaseAdd:
    pattern:  /suitcase/add/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:add }
    
suitcaseDelete:
    pattern:  /suitcase/delete/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:delete }
    
suitcaseFlag:
    pattern:  /suitcase/flag/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:flag }
    
suitcaseFlags:
    pattern:  /suitcase/flags
    defaults: { _controller: InertiaWinspireBundle:Suitcase:flags }
    
suitcasePack:
    pattern:  /suitcase/pack
    defaults: { _controller: InertiaWinspireBundle:Suitcase:pack }
    
suitcasePreview:
    pattern:  /suitcase/preview
    defaults: { _controller: InertiaWinspireBundle:Suitcase:preview }
    
suitcaseShare:
    pattern:  /suitcase/share
    defaults: { _controller: InertiaWinspireBundle:Suitcase:share }
    
suitcaseShareAgain:
    pattern:  /suitcase/reshare/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:shareAgain }
    
shareComment:
    pattern:  /comment/{id}/{token}
    defaults: { _controller: InertiaWinspireBundle:Share:comment, token: none }
    
shareView:
    pattern:  /share/{token}
    defaults: { _controller: InertiaWinspireBundle:Share:view }
    
accountCreate:
    pattern:  /account/new
    defaults: { _controller: InertiaWinspireBundle:Account:create }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
pageDisplay:
    pattern:  /{slug}
    defaults: { _controller: InertiaWinspireBundle:Page:display }
