# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_home:
    pattern:  /
    defaults: { _controller: InertiaWinspireBundle:Default:index }
    
plp:
    pattern:  /plp
    defaults: { _controller: InertiaWinspireBundle:Default:plp }