whitelabel_learn:
    host:     "{subdomain}.experiencecharity.com"
    path:     /learn-more
    defaults: { _controller: InertiaWinspireBundle:Default:learnMore }
    requirements:
        _scheme: http

whitelabel_search:
    host:     "{subdomain}.experiencecharity.com"
    path:     /search
    defaults: { _controller: InertiaWinspireBundle:Default:packageSearch }
    requirements:
        _scheme: http

whitelabel_thanks:
    host:     "{subdomain}.experiencecharity.com"
    path:     /thank-you
    defaults: { _controller: InertiaWinspireBundle:Default:thankYou }
    requirements:
        _scheme: http

whitelabel_detail:
    host:     "{subdomain}.experiencecharity.com"
    path:     /package/{slug}
    defaults: { _controller: InertiaWinspireBundle:Default:packageDetail }
    requirements:
        _scheme:  http

whitelabel_all:
    host:     "{subdomain}.experiencecharity.com"
    path:     /all
    defaults: { _controller: InertiaWinspireBundle:Default:packageListAll}
    requirements:
        _scheme: http

whitelabel_home:
    host:     "{subdomain}.experiencecharity.com"
    path:     /{slug}
    defaults: { _controller: InertiaWinspireBundle:Default:packageList, slug: all }
    requirements:
        _scheme: http


# if all else fails, we're throwing a 404
whitelabel_default404:
    host:     "{subdomain}.experiencecharity.com"
    path:     /{url}
    defaults: { _controller: InertiaWinspireBundle:Page:none, url: "none" }
    requirements:
        url: ".+"