# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_home:
    pattern:  /
    defaults: { _controller: InertiaWinspireBundle:Default:index }
    
<<<<<<< HEAD
_plp:
=======
plp:
>>>>>>> 608648182c4bc95655c2ff2accfda36d75ff8428
    pattern:  /plp
    defaults: { _controller: InertiaWinspireBundle:Default:plp }