# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

home:
    pattern:  /
    defaults: { _controller: InertiaWinspireBundle:Default:index }
    
packageList:
    pattern:  /packages/{slug}
    defaults: { _controller: InertiaWinspireBundle:Default:packageList, slug: all }
    
packageListJson:
    pattern:  /packages.json
    defaults: { _controller: InertiaWinspireBundle:Default:packageListJson }
    
packageDetail:
    pattern:  /package/{slug}
    defaults: { _controller: InertiaWinspireBundle:Default:packageDetail }
    
suitcaseAdd:
    pattern:  /suitcase/add/{id}
    defaults: { _controller: InertiaWinspireBundle:Suitcase:add }    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
