# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

home:
    pattern:  /
    defaults: { _controller: InertiaWinspireBundle:Default:index }
    
packageList:
    pattern:  /packages
    defaults: { _controller: InertiaWinspireBundle:Default:packageList }
    
packageDetail:
    pattern:  /package-detail
    defaults: { _controller: InertiaWinspireBundle:Default:packageDetail }