jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /suitcase
            logout: true
            anonymous: true

    access_control:
        - { path: ^/account, role: ROLE_USER }
        - { path: ^/account/edit, role: ROLE_USER }
        - { path: ^/suitcase, role: ROLE_USER }
        - { path: ^/suitcase/add, role: ROLE_USER }
        - { path: ^/suitcase/delete, role: ROLE_USER }
        - { path: ^/suitcase/flag, role: ROLE_USER }
        - { path: ^/suitcase/flags, role: ROLE_USER }
        - { path: ^/suitcase/kill, role: ROLE_USER }
        - { path: ^/suitcase/pack, role: ROLE_USER }
        - { path: ^/suitcase/preview, role: ROLE_USER }
        - { path: ^/suitcase/share, role: ROLE_USER }
        - { path: ^/suitcase/reshare, role: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
