jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_NP
        ROLE_SUPER_ADMIN: [ ROLE_NP, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /suitcase
            logout: true
            anonymous: true
            remember_me:
                key:      '%secret%'
                lifetime: 31536000 # 365 days in seconds
                name:     remember
                path:     /
                domain:   '%session_domain%'

    access_control:
        - { path: ^/account$, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/account/edit, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/admin/sf, role: ROLE_ADMIN }
        - { path: ^/partner, role: ROLE_PARTNER }
        - { path: ^/suitcase, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/suitcase/add, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/suitcase/create, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/suitcase/delete, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/suitcase/flag, role: ROLE_NP }
        - { path: ^/suitcase/flags, role: ROLE_NP }
        - { path: ^/suitcase/history, role: ROLE_NP }
        - { path: ^/suitcase/invoice, role: ROLE_NP }
        - { path: ^/suitcase/kill, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/suitcase/loa, role: ROLE_NP }
        - { path: ^/suitcase/pack, role: ROLE_NP }
        - { path: ^/suitcase/preview, role: ROLE_NP }
        - { path: ^/suitcase/share, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/suitcase/reshare, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/suitcase/request-invoice, role: ROLE_NP }
        - { path: ^/suitcase/preview-voucher, role: ROLE_NP }
        - { path: ^/suitcase/send-voucher, role: ROLE_NP }
        - { path: ^/suitcase/switch, roles: [ROLE_NP, ROLE_PARTNER] }
        - { path: ^/suitcase/update-booking, role: ROLE_NP }
        - { path: ^/suitcase/update-qty, role: ROLE_NP }
        - { path: ^/suitcase/update-price, role: ROLE_NP }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
